### ISSUE TITLE
Correct current DUB package

### ISSUE THREAD

**Issue by vladdeSV** [robik/ConsoleD#18]
The [current ConsoleD package](http://code.dlang.org/packages/consoled) is pointing to [Ianis G. Vasilev](https://github.com/v--)'s fork (I assume), which is not the most updated one and causes problems when building with dub.

This should also address #10

**Comment by vladdeSV** [comment]
@v-- You've registered your fork as the ConsoleD. Is there a chance you can change it or do we need @robik to also do something?

**Comment by v--** [comment]
I would gladly update the package so that it points to this repo, however there are no tagged versions and code.dlang.org requires at least one:

```
The repository must have at least one tagged version (SemVer format, e.g. "v1.0.0" or "v0.0.1") to be published on the registry. Please add a proper tag using "git tag" or equivalent means and see http://semver.org for more information.
```

**Comment by v--** [comment]
I have just merged my repo with this one and triggered a manual dub update, the changes should be upstream soon

**Comment by vladdeSV** [comment]
The dub registry still hasn't been updated, any thoughts on when it will? @v--

**Comment by v--** [comment]
I just updated my repo (again) and the dub package is now up to date. It may seem obvious, but I didn't know It's mandatory to add 'v' before your version in order to update a http://code.dlang.org package.

**Comment by v--** [comment]
The issue is resolved now.

@robik:
You should really start git 'tagging' your versions so I can redirect the dub package to your repo.

**Comment by vladdeSV** [comment]
@v--
I do not really want to close this, since this package isn't the one on dub right now. Once this package updates you need to update your own package. I would really want @robik to add a version. But, I will close this issue :)

**Comment by robik** [comment]
Sorry for horrible delay, version added.

I guess I have to check GitHub more often :/
