### ISSUE TITLE
Error: undefined identifier (TIOCGWINSZ & SIGWINCH)

### ISSUE THREAD

**Issue by afaur** [robik/ConsoleD#19]
```sh
Building consoled ~master configuration "library", build type debug.
Running dmd...
dmd -lib -of.dub/build/library-debug-posix.osx-x86_64-dmd_2066-07DFD2109FA006DAE4A88167876EDB72/libconsoled.a -debug -g -w -version=Have_consoled -Isource/ source/consoled.d source/terminal.d
source/consoled.d(759): Error: undefined identifier TIOCGWINSZ
source/terminal.d(1259): Error: undefined identifier SIGWINCH
source/terminal.d(1367): Error: undefined identifier SIGWINCH
FAIL .dub/build/library-debug-posix.osx-x86_64-dmd_2066-07DFD2109FA006DAE4A88167876EDB72/ consoled staticLibrary
Error executing command run:
dmd failed with exit code 1.
```

Not sure why i'm getting this exactly.. from my google searching it seems like these identifiers should resolve to values but they seem to be failing my build. 

```sh
Darwin local.localhost 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
```

**Comment by codewisdom** [comment]
I'm getting this too.   I'm on OS X 10.11.2. @afaur, did you resolve or workaround it?

**Comment by adamdruppe** [comment]
On Wed, Dec 16, 2015 at 04:57:27PM -0800, Sam wrote:
> I'm getting this too.   I'm on OS X 10.11.2. @afaur, did you resolve or workaround it?

I probably need to resync the repos cuz I'm pretty sure it is fixed.

Try it now...

**Comment by afaur** [comment]
Nope,  I gave up thinking Mac OSX was unsupported.  
Just cloned and tried to build.  It would be nice to be able to use this library if you do want to support other operating systems just let me know and I can test or try different dub configurations on my machine for you.

```
-> % dub --version
DUB version unknown, built on Apr  6 2015
-> % dmd --version
DMD64 D Compiler v2.067.0
Copyright (c) 1999-2014 by Digital Mars written by Walter Bright
-> % dub
Building consoled 1.0.0+commit.5.g744a9f3 configuration "library", build type debug.
Running dmd...
source/consoled.d(766): Error: undefined identifier TIOCGWINSZ
FAIL .dub/build/library-debug-posix.osx-x86_64-dmd_2067-20BE56C3FE07EA86CFA975B52A2D9C27/ consoled staticLibrary
Error executing command run:
dmd failed with exit code 1.
```

**Comment by vladdeSV** [comment]
I have this in my code:
```d
version (OSX)
{
    //Special code for OS X.
    enum TIOCGWINSZ = 0x40087468;
}
```

Test to see if it solves the problem, for TIOCGWINSZ atleast?

**Comment by vladdeSV** [comment]
Also, looking around I found

```d
enum SIGWINCH = 28;
```

Test that too?

**Comment by vladdeSV** [comment]
ping @afaur @codewisdom

**Comment by adamdruppe** [comment]
My terminal.d has OS X support now... not sure about the console.d though, but copy/pasting the values might be all you need.

 version(OSX) {
                import core.stdc.config;
                extern(C) int ioctl(int, c_ulong, ...);
                enum TIOCGWINSZ = 1074295912;
}

different than linux btw!

And winch is the same on all posix:

        enum SIGWINCH = 28;

**Comment by afaur** [comment]
So, I was able to get it to compile however it looks like the underlying issue for me was that `TIOCGWINSZ` was undefined inside `consoled.d` file all together.  I guess since it is defined inside of `terminal.d` it isn't able to be read properly on `line 766` of `consoled.d` I ended up having to put a number there in place of the `TIOCGWINSZ` so that it looks like `ioctl(STDOUT_FILENO, 1074295912, &w);`.  It compiled successfully however I guess depending on if that value is the correct one for my OS or not would not be apparent until I use the library.   Is there a test that could be run as part of this codebase that would assert that it works given the os i'm running the test on?

**Comment by codewisdom** [comment]
@vladdeSV I tried your approach and it worked for me! :+1:

**Comment by e10s** [comment]
At least, `size()` might have to try to obtain the symbols explicitly from `terminal.d` rather than from druntime because `core.sys.posix.sys.ioctl`, which provides `TIOCGWINSZ` for some environments and also `ioctl()` for some systems, has already been imported into `console.d`.

The way below looks fine:
```d
static import terminal;
terminal.ioctl(STDOUT_FILENO, terminal.TIOCGWINSZ, &w);
```

**Comment by SingingBush** [comment]
I just stumbled into this problem trying to build my project on OSX. any chance of getting the fix into a new release on the dub repo? 

```bash
Performing "debug" build using dmd for x86_64.
consoled 1.0.1: building configuration "library"...
../../../.dub/packages/consoled-1.0.1/source/consoled.d(766,30): Error: undefined identifier 'TIOCGWINSZ'
../../../.dub/packages/consoled-1.0.1/source/consoled.d(1206,15): Deprecation: module std.array is not accessible here, perhaps add 'static import std.array;'
dmd failed with exit code 1.
```
